/** Tangerine compiler. Source values live in tokens.json; never edit generated files. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const source = JSON.parse(fs.readFileSync(path.join(dir, 'tokens.json'), 'utf8'));
const check = process.argv.includes('--check');
const isToken = x => x && typeof x === 'object' && '$value' in x;
const flatten = (obj, prefix = '', out = {}) => {
  for (const [key, value] of Object.entries(obj)) {
    const name = prefix ? `${prefix}.${key}` : key;
    if (isToken(value)) out[name] = value;
    else flatten(value, name, out);
  }
  return out;
};
const base = flatten(source.foundation);
const resolved = {}, maps = {};
for (const mode of ['light', 'dark']) {
  const map = { ...base, ...flatten(source.modes[mode]), ...flatten(source.components, 'component') };
  const allowedTypes = new Set(['dimension','duration','fontFamily','cubicBezier','gradient','shadow','breakpoint','number','color']);
  for (const [key, token] of Object.entries(map)) {
    if (!allowedTypes.has(token.$type)) throw Error(`Unknown type at ${key}`);
    const value=token.$value;
    if(typeof value==='string' && /^\{[^}]+\}$/.test(value)) {
      const target=map[value.slice(1,-1)];
      if(!target) throw Error(`Unknown token ${value} at ${key}`);
      if(target.$type!==token.$type) throw Error(`Alias type mismatch at ${key}`);
    }
  }
  maps[mode] = map;
  const resolve = (key, trail = []) => {
    if (!map[key]) throw Error(`Unknown token ${key}`);
    if (trail.includes(key)) throw Error(`Cyclic token ${trail.join(' -> ')} -> ${key}`);
    const visit = value => {
      if (typeof value === 'string' && /^\{[^}]+\}$/.test(value)) {
        const ref = value.slice(1, -1);
        return resolve(ref, [...trail, key]);
      }
      if (Array.isArray(value)) return value.map(visit);
      if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k,v]) => [k, visit(v)]));
      return value;
    };
    return visit(map[key].$value);
  };
  resolved[mode] = Object.fromEntries(Object.keys(map).map(k => [k, resolve(k)]));
  for(const [key,value] of Object.entries(resolved[mode])) {
    const type=map[key].$type;
    if(['dimension','duration','breakpoint','number'].includes(type) && (!Number.isFinite(value)||value<0)) throw Error(`Invalid numeric token ${key}`);
    if(type==='color' && !/^#[0-9a-f]{6}$|^rgba\([\d., ]+\)$/i.test(value)) throw Error(`Invalid color ${key}`);
    if(type==='fontFamily' && (!Array.isArray(value)||!value.length||value.some(v=>typeof v!=='string'))) throw Error(`Invalid font family ${key}`);
    if(type==='cubicBezier' && (!Array.isArray(value)||value.length!==4||value.some(v=>!Number.isFinite(v))||value[0]<0||value[0]>1||value[2]<0||value[2]>1)) throw Error(`Invalid easing ${key}`);
  }
}
if (Object.keys(resolved.light).join() !== Object.keys(resolved.dark).join()) throw Error('Theme token keys differ');
const kebab = s => s.replace(/[A-Z]/g, m => '-' + m.toLowerCase()).replaceAll('.', '-');
const variable = k => `--ed-${kebab(k)}`;
const cssValue = (key, value, type) => {
  if (type === 'dimension') return `${value / 16}rem`;
  if (type === 'duration') return `${value}ms`;
  if (type === 'fontFamily') return value.map(s => s.includes(' ') ? `"${s}"` : s).join(', ');
  if (type === 'cubicBezier') return `cubic-bezier(${value.join(', ')})`;
  if (type === 'gradient') return `linear-gradient(${value.angle}deg, ${value.stops.join(', ')})`;
  if (type === 'shadow') return `${value.x}px ${value.y}px ${value.blur}px ${value.spread}px ${value.color}`;
  if (type === 'breakpoint') return `${value}px`;
  if (typeof value === 'object') throw Error(`Unhandled ${key}: ${type}`);
  return String(value);
};
let css = '/* GENERATED by build.mjs. Import once. Explicit data-theme is set by the theme provider. */\n';
for (const mode of ['light', 'dark']) {
  css += `${mode === 'light' ? ':root, [data-theme="light"]' : '[data-theme="dark"]'} {\n  color-scheme: ${mode};\n`;
  for (const [key, token] of Object.entries(maps[mode])) {
    // Keep references live so one overridden semantic role flows into every component.
    const value = typeof token.$value === 'string' && /^\{[^}]+\}$/.test(token.$value)
      ? `var(${variable(token.$value.slice(1,-1))})` : cssValue(key, resolved[mode][key], token.$type);
    css += `  ${variable(key)}: ${value};\n`;
  }
  css += '}\n';
}
const nest = flat => {
  const out = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split('.'); let current = out;
    for (const part of parts.slice(0,-1)) current = current[part] ??= {};
    current[parts.at(-1)] = value;
  }
  return out;
};
const themes = Object.fromEntries(Object.entries(resolved).map(([k,v]) => [k,nest(v)]));
const json = JSON.stringify(themes, null, 2);
const ts = `// GENERATED by build.mjs. Dimensions: logical px / native dp; font sizes: scalable native units.\n// Web uses tokens.css (rem). Native resolves registered fonts and gradient/shadow adapters.\nexport const themes = ${json} as const;\nexport type ThemeMode = keyof typeof themes;\nexport type Theme = (typeof themes)[ThemeMode];\nexport type TokenName = ${Object.keys(resolved.light).map(k => JSON.stringify(k)).join(' | ')};\nexport const cssVariables = ${JSON.stringify(Object.fromEntries(Object.keys(resolved.light).map(k=>[k,`var(${variable(k)})`])),null,2)} as const;\n`;
const luminance = hex => {
  const rgb = hex.replace('#','').match(/../g).map(v => parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);
  return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;
};
const ratio = (a,b) => (Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);
const results = [];
for (const mode of ['light','dark']) {
  const v = resolved[mode];
  for (const pair of source.contrastPairs) {
    const score = ratio(v[pair.foreground],v[pair.background]);
    results.push({mode,...pair,ratio:Number(score.toFixed(2)),pass:score>=pair.minimum});
  }
  // Sample the complete sRGB gradient, including interpolation between every pair of stops.
  for (const name of ['brand','ai']) {
    const stops=v[`gradient.${name}`].stops;
    const fg=v[`color.${name}.onGradient`]; let minimum=Infinity;
    for(let i=0;i<stops.length-1;i++) for(let step=0;step<=100;step++) {
      const channels=h=>h.slice(1).match(/../g).map(x=>parseInt(x,16));
      const a=channels(stops[i]), b=channels(stops[i+1]);
      const hex='#'+a.map((x,j)=>Math.round(x+(b[j]-x)*step/100).toString(16).padStart(2,'0')).join('');
      minimum=Math.min(minimum,ratio(fg,hex));
    }
    results.push({mode,foreground:`color.${name}.onGradient`,background:`gradient.${name}`,minimum:4.5,ratio:Number(minimum.toFixed(2)),pass:minimum>=4.5});
  }
}
if (results.some(r=>!r.pass)) throw Error(`Contrast failures: ${JSON.stringify(results.filter(r=>!r.pass))}`);
let reference = '# Tangerine token reference\n\nGenerated from [tokens.json](tokens.json). Edit the source, then run `node design/system/tangerine/build.mjs`.\n\nCSS names use `--ed-` and kebab case; TypeScript uses the dotted paths below. Dimensions are logical px (web output is rem, 16px reference); durations are ms. Breakpoints are px. Numbers are unitless. Component values resolve from semantic tokens.\n\n| Token | Type | Light | Dark | Purpose |\n|---|---|---|---|---|\n';
for (const [key,token] of Object.entries(maps.light)) {
  const show=v=>typeof v==='object'?JSON.stringify(v):String(v);
  reference+=`| \`${key}\` | ${token.$type} | ${show(resolved.light[key])} | ${show(resolved.dark[key])} | ${token.$description||'—'} |\n`;
}
const outputs={'tokens.css':css,'tokens.ts':ts,'tokens.resolved.json':json+'\n','TOKENS.md':reference,'contrast-report.json':JSON.stringify({tokenCount:Object.keys(resolved.light).length,checks:results.length,results},null,2)+'\n'};
for (const [name,content] of Object.entries(outputs)) {
  const target=path.join(dir,name);
  if(check) { if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==content) throw Error(`Stale generated file: ${name}`); }
  else fs.writeFileSync(target,content);
}
console.log(`${check?'Verified':'Generated'} ${Object.keys(outputs).length} files; ${Object.keys(resolved.light).length} tokens per theme; ${results.length} contrast checks passed.`);
